### ISSUE TITLE
Automatically add a file to source control when it's been added to a project

### ISSUE THREAD

**Issue by ddobrev** [jzoss/Git-Source-Control-Provider#53]
I kept forgetting to request this feature even though it's been the only annoyance I've had with this add-in since the very beginning (Yiyi Sun's work). It would be really convenient to auto-add a new file the moment it's added to a project, or a solution, while at the same time I don't think there are any down sides. Now I have to open Windows Explorer each time to add the file with Tortoise Git.

**Comment by jzoss** [comment]
Feel free to check out the latest C.I. build.. This feature is halfway done.. By that I mean.. I added a option to auto add the files and it works when you add a file to a project. It does not work yet when you add a whole new project.

**Comment by ddobrev** [comment]
Hello @jzoss , I am afraid I have been really busy to test this but I am sure you did an excellent job as usual. I can wait for the final release.

**Comment by jzoss** [comment]
@ddobrev You can check the latest C.I. build.. things are working .. Just a note .. for now if you add a project.. you need to right click on it, go to the scc menu and say add project.

**Comment by jzoss** [comment]
Done for 1.6.5

**Comment by ddobrev** [comment]
@jzoss the adding of files seems to have regressed, it doesn't work in VS 2017.

**Comment by ddobrev** [comment]
@jzoss "Add to Project" still appears and works but auto-adding just files doesn't. Could you please reopen this issue?

**Comment by jzoss** [comment]
Ok I will check it out

**Comment by ddobrev** [comment]
@jzoss thank you very much, you're the best. :)

**Comment by jzoss** [comment]
Do me a favor.. Try and include a file in a project and see if that gets added. Also.. make sure the option is checked to add files.. not sure if that could have been messed up in the last update.. It's working for me.. which usually means some odd error I missed

**Comment by ddobrev** [comment]
@jzoss it does not get added. About the option, I didn't know there was one. Where can I find it?

**Comment by jzoss** [comment]
Tool -> options .. source control options I think. I'm away from my desk at.

**Comment by ddobrev** [comment]
I am unfortunately unable to find such an option. Let me know if I can help later when you are at your computer.

**Comment by jzoss** [comment]
Tools -> Options -> Source Control -> Ez Git Options

**Comment by ddobrev** [comment]
In there I can only see options for paths and for expanding commands.

**Comment by jzoss** [comment]
should see 
![image](https://user-images.githubusercontent.com/3586254/30398443-f81d7328-9895-11e7-834f-e5e6becb9385.png)

**Comment by ddobrev** [comment]
@jzoss I cannot describe how sorry I am for wasting your time. Because I had kept this screen at its default size, I had been unable to see the options below the selection of a diff tool. All I had to do was enlarge the window a little and I saw all options. Both options for addition were turned off and when I marked them, it worked immediately.

Having said that, I was able to think of a few suggestions to improve your user experience so that this no longer happens:
1. Why don't you simply mark the options by default? They are really useful so there's no harm in doing it. The only minor inconvenience might occur in the case of projects with the stupid Class1-like files Visual Studio adds by default because they would be added to source control just to be immediately deleted. But you could skip such files when adding to Git;
2. You could move the options below right below the options above. This way it would be visible there's something more to uncover by resizing;
3. An improved version of 2 would be thinking of a different layout so that all options are visible with the default size of the window.

And, of course, thank you very much for taking the time and effort to solve my problem. Cheers. :)

**Comment by jzoss** [comment]
It's no problem.. I'm sure i could make a better layout. I can't remember why I decided to not enable by default.. I think I did not want to change how it was working for everyone.. I can't remember for sure. 

Don't worry you didn't waste my time. I like when people actually take a interest in this add-on it's the only way I know people are still using it.. 

BTW: In the Help wanted section of the readme.. I think I said something about if anyone wants to redo the Options page.. I'd be cool with that.. It's a bit of a mess!
